databases:
  - name: CareLoop-db
    plan: free
    postgresMajorVersion: "16"
    databaseName: careloop_production
    user: careloop
    region: singapore

services:
  - type: web
    name: CareLoop
    runtime: image  
    plan: free
    region: singapore
    image: 
      url: takumi333/careloop-back:latest
      creds:
        fromRegistryCreds:
          name: Docker_Hub_Credentials
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: CareLoop-db
          property: connectionString